pipeline {
  agent {
    label '482-build-agent'
  }
  stages {
    stage('Make') {
      steps {
	echo 'Make libpdpgo'
        sh 'make libpdpgo'
      }
    }
    stage('Copy builded lib') {
      steps {
        echo 'Copy builded lib'
        sh 'cp libpdpgo/build/release/lib/libpdpgo.a /home/ubuntu/go_path/src/github.com/proximax-storage/go-xpx-pdp/vendor/libpdpgo/lib/libpdpgo.a'
      }
    }
  }
  post {
    success {
        slackSend channel: '#devops_storage',
            color: 'good',
            message: "Branch *${env.GIT_BRANCH}* build of *${currentBuild.fullDisplayName}* completed successfully :100:"
    }
    failure {
        slackSend channel: '#devops_storage',
            color: 'bad',
            message: "Branch *${env.GIT_BRANCH}* of *${currentBuild.fullDisplayName}* FAILED :scream:"
    }
  }
}
