pipeline {
  agent {
    label '482-build-agent'
  }
  stages {
    stage('Make') {
      steps {
        withCredentials([sshUserPrivateKey(credentialsId: "keyserverprox", keyFileVariable: 'keyfile')]) {
            sh 'cp ${keyfile} ./id_rsa'
            sh 'docker build -t libpdp -f DockerfileFullCI .'
        }
      }
    }
  }
  post {
    success {
        slackSend channel: '#devops_storage',
            color: 'good',
            message: "Branch *${env.GIT_BRANCH}* build of *${currentBuild.fullDisplayName}* completed successfully :100:"
    }
    failure {
        slackSend channel: '#devops_storage',
            color: 'bad',
            message: "Branch *${env.GIT_BRANCH}* of *${currentBuild.fullDisplayName}* FAILED :scream:"
    }
  }
}
